name: social_recipe_app
description: A social recipe app to keep track of new dishes, and share with friends.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
